packages:
  - apps/*
  - services/*
  - packages/*
allowBuilds:
  better-sqlite3: true
  core-js: true
  electron: true
  electron-winstaller: false
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
